# @baseUrl=https://json-server-demoo.herokuapp/api
@baseUrl=http://localhost:4000/api
@resourceName=donations

# @name getAllproducts
GET {{baseUrl}}/{{resourceName}}

###
# @name filterProduct
GET {{baseUrl}}/{{resourceName}}?price_gte=900&color=teal

###

# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?name_like=Con


###

# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=2&_limit=5

###

# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=asc

###

# @name addNewproducts
# POST {{baseUrl}}
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "amount": 1700,
    "paymentType": "Direct",
    "upvotes": 0
}

###


# @name updateNewproducts
PATCH {{baseUrl}}/{{resourceName}}/4r2GN6f
Content-Type: application/json

{
    "name": "Licensed AAA Chair",
    "color": "blue",
    "price": 600
}


###


# @name Delete
DELETE  {{baseUrl}}/{{resourceName}}
Content-Type: application/json



